name: fortune_wheel_demo
version: 1.0.0

publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  auto_route: ^1.0.2
  flutter_hooks: ^0.16.0
  flutter_fortune_wheel:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  auto_route_generator: 1.0.2
  build_runner: 1.0.2

dependency_overrides:
  meta: 1.6.0

flutter:
  uses-material-design: true
